<!--
  Aside from the demo, the site pages are simply generated by markdown files in the project's github repository.Documentation
  Links to other files in the repo should redirect to the corresponding page on the site. This page intercepts any request ending
  in .md, and then redirects to the appropriate page.

-->
<script context="module">
  export async function preload(page, session) {
    const { slug } = page.params;

    return { slug: slug.toLowerCase() };
  }
</script>

<script>
  import { goto } from '@sapper/app';

  export let slug;

  if (slug === 'readme') slug = '';

  goto(slug, { replaceState: true });
</script>


